- name: Working with simple dictionaries
  hosts: localhost
  gather_facts: no
  
  vars:
    fruit:
      - 'orange'
      - 'lemon'
    snack:
      - 'cookie'
    vegetable:
      - 'carrot'
  
  tasks:

  - name: Loop across complex data structures
    debug:
      msg: "{{ item.name }} belongs in the {{ item.groups }} aisle"
    loop:
      - { name: "{{fruit}}", groups: 'fruit' }
      - { name: "{{snack}}", groups: 'snack' }
      - { name: "{{vegetable}}", groups: 'vegetable' }

