---
- name: Template with a loop
  hosts: fry
  connection: ssh
  gather_facts: no

  # these variables are used in the template ship.cfg.j2
  vars:
    mission:
     - "primary"
     - "secondary"
    planet:
     - "luna park"
     - "cineplex 14"
    

  tasks:
    - name: Running a looping jinja template
      template:  
        src: templates/mission-orders.txt.j2    # name of the template on ansible controller
        dest: "~/{{ item.mission }}-mission-orders.txt"
      loop:
        - {"mission": "{{mission[0]}}", "planet": "{{planet[0]}}"}
        - {"mission": "{{mission[1]}}", "planet": "{{planet[1]}}"}

